stages: 
  stage1:
    cmd: python stage1.py
    deps:
      - stage1.py
    outs:
      - artifacts01.txt
  
  stage2:
    cmd: python stage2.py
    deps:
      - artifacts01.txt
      - stage2.py
    
  stage3:
    cmd: python stage3.py
    deps:
      - artifacts01.txt
      - stage3.py
    outs:
      - artifacts02.txt  