stages: 
  stage1:
    cmd: python stage1.py
    deps:
      - stage1.py
    outs:
      - artifacts01.txt
  
  stage2:
    cmd: python stage2.py
    deps:
      - artifacts01.txt
      - stage2.py
    